### ISSUE TITLE
Esp32 port

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [tvlad1234/pico-rv32ima#12]
Hello,
Is it possible to port this over to the esp32? If yes, what files do I need to change? Also, how to use sd card as ram instead of psram?

**Comment by ElectroBoy404NotFound** [comment]
> It has been ported to esp32, see [this project](https://github.com/xhackerustc/uc-rv32ima/).

It uses a PS-RAM, which am trying to avoid. I can build an emulator form scratch using this project as base, but need help on using SD-RAM insted of PS-RAM

**Comment by tvlad1234** [comment]
Dmitry Grinberg's Linux AVR project uses SDRAM. There are also some SDRAM libraries for Arduino. I'd suggest using those as a reference when implementing SDRAM into your project. 

Using SDRAM instead of PSRAM is not within the scope of this project and as such, I won't be able to provide guidance on that.
