### ISSUE TITLE
spi ram

### ISSUE THREAD

**Issue by fanoush** [tvlad1234/pico-rv32ima#2]
You can get cheap 8MB 3.3V SPI RAM from https://www.aliexpress.com/item/4000164056594.html
 Or even multiple of them would work with shared SPI and separate cs pins per each 8MB adress range.

Just gooogle "ly68l6400 datasheet" for details, it mostly works just as SPI flash. Definitely easier than using SD.

**Comment by tvlad1234** [comment]
Thank you for your suggestion! I have considered using SPI RAM from the beginning, but I didn't have any on hand. I have just ordered some from the link you posted and I'll try using them as soon as they arrive. In case you or anyone else manages to get this project working with SPI RAM before I can get my hands on the chips, please submit a PR and I'll be more than happy to accept it into the repository.

**Comment by tvlad1234** [comment]
The SPI RAM chips have arrived today. I have successfully implemented them into the project. Linux now boots to the shell in about 5 minutes and it's (relatively speaking) usable. Once again, thank you so much for sending me the link to these RAM chips.

**Comment by fanoush** [comment]
Oh, that was fast!  You're welcome, it is great that it is working for you :-) This cheap part needs to be more widely known, it is very simple to add to any project where more RAM is needed.

**Comment by flyboy-byte** [comment]
hello, im am currently purchasing parts to build this project, i ran across this ram chip. https://protosupplies.com/product/psram/ , they offer 4 different ram including the one specified in the readme of this project. but it turns out they are all essentially the same chip according to one source i found. so if u wanted to purchase from this site instead, im sure you would not have to wait months on parts from china. also protosupplies seems like a great website.
